# Generated by Django 4.2.3 on 2023-07-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="like_count",
            field=models.IntegerField(),
        ),
    ]
