# Generated by Django 4.2.3 on 2023-07-17 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_feed_like_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feed",
            old_name="profile_name",
            new_name="profile_image",
        ),
    ]
