# Generated by Django 4.2.3 on 2023-08-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_rename_profile_name_feed_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feed",
            name="profile_image",
        ),
        migrations.RemoveField(
            model_name="feed",
            name="user_id",
        ),
        migrations.AddField(
            model_name="feed",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
