# Generated by Django 4.2.3 on 2023-08-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_remove_feed_profile_image_remove_feed_user_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_id", models.IntegerField(default=0)),
                ("email", models.EmailField(default="", max_length=254)),
                ("is_marked", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_id", models.IntegerField(default=0)),
                ("email", models.EmailField(default="", max_length=254)),
                ("is_like", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_id", models.IntegerField(default=0)),
                ("email", models.EmailField(default="", max_length=254)),
                ("reply_content", models.TextField()),
            ],
        ),
    ]
