# Generated by Django 4.2.3 on 2023-08-02 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_bookmark_like_reply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feed",
            name="like_count",
        ),
    ]
